name: blacklist
description: "Stock Application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.5
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  icons_plus: ^5.0.0
  lottie: ^3.0.0
  animated_flip_counter: ^0.2.6
  date_format: ^2.0.7
  flutter_animated_button: ^2.0.3
  animated_loading_border: ^0.0.2
  fluttertoast: ^8.2.4
  crypto: ^3.0.3
  data_table_2: ^2.5.10
  pretty_qr_code: ^3.2.1
  comment_tree: ^0.3.0
  searchfield: ^0.9.2
  hive: ^2.2.3
  fl_chart: ^0.66.2
  uuid: ^4.3.3
  qr_code_dart_scan: ^0.7.5
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
